version: "3.9"

services:
  app:
    env_file:
      - app/.env
    container_name: chat_api
    build:
      context: .
    ports:
      - "${FORWARD_APP_PORT:-8000}:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      DEV: true

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8091:8001'
    volumes:
      - 'redisinsight:/db'

  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

volumes:
  redisinsight:
  sail-redis: